### ISSUE TITLE
Все время показывает 1 руб.

### ISSUE THREAD

**Issue by rejedai** [enxy0/Plantain#3]
Пробовал 2 разные карты, иногда читает правильно.

Android 12, на 11 приложение работало правильно.

![Screenshot_20220217-125250_Plantain](https://user-images.githubusercontent.com/92713267/154452636-4ca73227-2912-4e69-9353-fb8eda2ce0aa.png)

![Screenshot_20220217-130349_Plantain](https://user-images.githubusercontent.com/92713267/154452698-7fbf9924-8d9d-4a57-a47c-77cc2cbb22e3.png)

**Comment by enxy0** [comment]
@rejedai к сожалению не могу посмотреть твою ошибку, вероятно в новой прошивке вендор твоего устройства где-то накосячил и неправильно считывает `MifareClassic` тег. Можешь через [MifareClassicTool](https://github.com/ikarus23/MifareClassicTool ) сделать дамп 4 и 5 сектора и прислать его сюда? Это поможет понять проблема в приложении или косяк вендора

**Comment by rejedai** [comment]
Да, я разобрался с ошибкой, фиксится выключением легаси в `/product/etc/libnfc-nci.conf` заменить в параметре `LEGACY_MIFARE_READER` единицу на нуль.
