### ISSUE TITLE
Краш при запуске

### ISSUE THREAD

**Issue by kewldan** [enxy0/Plantain#4]
При запуске приложение моментально крашится. Ключи взял из Debug файла (Идентичны ключам из [статьи](https://sohabr.net/habr/post/324040/))
[local.properties.txt](https://github.com/enxy0/Plantain/files/9640483/local.properties.txt)
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/40865857/192138509-cf9c9371-7b29-45f8-b940-fee47bae9ffc.png">
<img width="256" alt="image" src="https://user-images.githubusercontent.com/40865857/192138519-9255cf68-647a-45ba-9ca9-f0046c6f9e72.png">

**Comment by enxy0** [comment]
APK можно взять из [Releases](https://github.com/enxy0/Plantain/releases) соответствующей версии. А конкретно этот баг подправил в версии [2.5](https://github.com/enxy0/Plantain/releases/tag/v2.5), теперь проект должен нормально собираться 🙂
